UppercaseOrLawermake: UppercaseOrLowercase.cc
	
	g++ -std=c++17 -Wall -c UppercaseOrLowercase.cc
	g++ -o UppercaseOrLowercase UppercaseOrLowercase.o
	
.PHONY:	all clean

	$(CXX) $(CXXFLAGS) -c $<
clean:
        
	rm -rf *.o 
	rm -rf UppercaseOrLowercase

