TopToBottom: TopToBottom.cc
	g++ -std=c++17 -Wall -c TopToBottom.cc TopToBottom.cc
	g++ -o TopToBottom TopToBottom.o

.PHONY: all clean

	$(CXX) $(CXXFLAGS) -c $<
clean:

	rm -rf *.o
	rm -rf TopToBottom


